name             'osl-opensearch-test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Installs/Configures osl-opensearch-test'
version          '0.1.0'
depends          'osl-opensearch'
