name              'osl-opensearch'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-opensearch'
issues_url        'https://github.com/osuosl-cookbooks/osl-opensearch/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-opensearch'
chef_version      '>= 18.0'
version           '0.1.0'

supports          'almalinux', '~> 8.0'
supports          'almalinux', '~> 9.0'
